spring:
  application:
    name: greeting-service
  cloud:
    config:
      enabled: false
greeting-service:
  name: "Rafael"
  defaultValue: "welcome!"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always